server:
  port: 8080
  servlet:
    context-path: / #项目的上下文路径
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatBot?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    check-template-location: true
#    suffix: .html
#    encoding: utf-8
#    mode: HTML
  mvc:
   static-path-pattern: /static/**
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml #加载映射文件
  type-aliases-package: com.moderatePerson.domain #别名搜索的包
  configuration:
    lazy-loading-enabled: true #打开懒加载
    aggressive-lazy-loading: false #关闭积极懒加载
    map-underscore-to-camel-case: false